DIR=fx
SYM_LINK=gx
SOCKET=ex
PIPE=dx
EXE=cx
BLOCK_SP=dx
CHAR_SP=dx
EXE_SUID=hb
EXE_GUID=ad
DIR_STICKY=Fx
DIR_WO_STICKY=Fx

export LSCOLORS="$DIR$SYM_LINK$SOCKET$PIPE$EXE\
$BLOCK_SP$CHAR_SP$EXE_SUID$EXE_GUID\
$DIR_STICKY$DIR_WO_STICKY"

export CLICOLOR="YES"
